### ISSUE TITLE
Concat a string with PHP

### ISSUE THREAD

**Issue by kthrock** [formalms/formalms#22]
There is an error with version 4.0.7 on the Authentication API. In the file:

api\lib\api.auth.php

https://github.com/formalms/formalms/blob/61212eb148e765a41bbc7648592789742d98627f/html/api/lib/api.auth.php#L73

Line 73:
`$token = md5(uniqid(rand(), true) + $username);`

It throws a Fatal PHP Error of String + String error.

I changed it to:

`$token = md5(uniqid(rand(), true) . $username);`

Is this an issue or is there something I am missing?

**Comment by formalms** [comment]
it's a issue.
with php version prior to 8.0 the the code does not raise a "Fatal error" but only a warning 
The proposed solution is good

**Comment by eduardomozart** [comment]
This was already fixed in FormaLMS 3.3.24 as seen in: https://github.com/formalms/formalms/blob/master/html/api/lib/api.auth.php#L73

This issue can be closed. Thank you for your contribution.
